# Generated by Django 5.1.4 on 2025-08-04 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nhcx', '0003_coverageeligibilityrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('intent', models.CharField(max_length=100)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.JSONField(blank=True, null=True)),
                ('authored_on', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reason_code', models.JSONField(blank=True, null=True)),
                ('input', models.JSONField(blank=True, default=list, null=True)),
                ('output', models.JSONField(blank=True, default=list, null=True)),
                ('use_case', models.CharField(choices=[('communication_request', 'Communication Request'), ('communication_response', 'Communication Response'), ('payment_notice_request', 'Payment Notice Request'), ('payment_notice_response', 'Payment Notice Response'), ('reprocess_request', 'Reprocess Request'), ('reprocess_response', 'Reprocess Response'), ('search_request', 'Search Request'), ('search_response', 'Search Response'), ('insurance_plan_request', 'Insurance Plan Request')], max_length=32)),
                ('focus_id', models.PositiveIntegerField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhcx.claim')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('focus_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('part_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhcx.task')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('identifier', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.JSONField(blank=True, default=list, null=True)),
                ('authored_on', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=list, null=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhcx.claim')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhcx.communicationrequest')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('based_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhcx.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=100)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.JSONField(blank=True, default=list, null=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=list, null=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhcx.claim')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('based_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhcx.communicationrequest')),
                ('part_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhcx.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
