# Generated by Django 5.1.4 on 2025-08-05 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0031_rename_reason_for_visit_tokenbooking_note'),
        ('nhcx', '0004_task_communicationrequest_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageeligibilityrequest',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.encounter'),
        ),
    ]
