# Generated by Django 5.1.4 on 2025-08-08 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhcx', '0006_paymentreconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhcx.claim'),
        ),
    ]
