# Generated by Django 5.1.4 on 2025-08-08 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhcx', '0007_alter_task_claim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('identifier', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('extension', models.JSONField(blank=True, default=list, null=True)),
                ('product_identifier', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=100)),
                ('type', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.JSONField(blank=True, default=list, null=True)),
                ('period', models.JSONField(default=dict)),
                ('contact', models.JSONField(blank=True, default=list, null=True)),
                ('coverage', models.JSONField(default=list)),
                ('plan', models.JSONField(blank=True, default=list, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhcx.task')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
