# Generated by Django 6.0 on 2026-04-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhcx', '0009_memberbiometricauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='use_case',
            field=models.CharField(choices=[('communication_request', 'Communication Request'), ('communication_response', 'Communication Response'), ('payment_notice_request', 'Payment Notice Request'), ('payment_notice_response', 'Payment Notice Response'), ('reprocess_request', 'Reprocess Request'), ('reprocess_response', 'Reprocess Response'), ('cancel_request', 'Cancel Request'), ('cancel_response', 'Cancel Response'), ('search_request', 'Search Request'), ('search_response', 'Search Response'), ('insurance_plan_request', 'Insurance Plan Request')], max_length=32),
        ),
    ]
