# Generated by Django 6.0 on 2026-05-17 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhcx', '0012_insuranceplan_insuranceplancoverage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NHCXInboundEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('api_call_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('callback_type', models.CharField(choices=[('coverageeligibility_on_check', 'coverageeligibility/on_check'), ('predetermination_on_submit', 'predetermination/on_submit'), ('preauth_on_submit', 'preauth/on_submit'), ('claim_on_submit', 'claim/on_submit'), ('communication_request', 'communication/request'), ('paymentnotice_request', 'paymentnotice/request'), ('insuranceplan_on_request', 'insuranceplan/on_request'), ('task_on_submit', 'task/on_submit'), ('error_response', 'error/response')], db_index=True, max_length=64)),
                ('recipient_code', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_payload', models.TextField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['callback_type', 'correlation_id'], name='nhcx_nhcxin_callbac_9edb56_idx'), models.Index(fields=['status', 'callback_type'], name='nhcx_nhcxin_status_e4ceb7_idx')],
            },
        ),
    ]
