# Generated by Django 6.0 on 2026-05-17 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhcx', '0013_nhcxinboundenvelope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplancoverage',
            name='type_display',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='insuranceplancoveragebenefit',
            name='type_display',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='insuranceplanplanspecificcostbenefit',
            name='type_display',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='insuranceplanquestionnaire',
            name='full_url',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='InsurancePlanBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('coverage_type_code', models.CharField(db_index=True, max_length=64)),
                ('coverage_type_display', models.CharField(blank=True, default='', max_length=255)),
                ('type_code', models.CharField(db_index=True, max_length=64)),
                ('type_display', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('plan_type_code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('plan_type_display', models.CharField(blank=True, default='', max_length=255)),
                ('specialty_category_code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('specialty_category_display', models.CharField(blank=True, default='', max_length=255)),
                ('coverage_benefit_fhir_ids', models.JSONField(blank=True, default=list)),
                ('min_cost', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=14, null=True)),
                ('max_cost', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=14, null=True)),
                ('max_limit_amount', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_count', models.PositiveSmallIntegerField(default=0)),
                ('qualifier_count', models.PositiveSmallIntegerField(default=0)),
                ('authorization_required', models.BooleanField(db_index=True, default=True)),
                ('is_day_care', models.BooleanField(blank=True, db_index=True, null=True)),
                ('implant_applicable', models.BooleanField(blank=True, db_index=True, null=True)),
                ('stratification_allowed', models.BooleanField(blank=True, db_index=True, null=True)),
                ('procedure_type', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('has_copayment', models.BooleanField(db_index=True, default=False)),
                ('has_deductible', models.BooleanField(db_index=True, default=False)),
                ('has_waiting_period', models.BooleanField(db_index=True, default=False)),
                ('has_stratification_qualifier', models.BooleanField(db_index=True, default=False)),
                ('has_implant_qualifier', models.BooleanField(db_index=True, default=False)),
                ('has_consumable_qualifier', models.BooleanField(db_index=True, default=False)),
                ('has_questionnaire', models.BooleanField(db_index=True, default=False)),
                ('questionnaire_fhir_ids', models.JSONField(blank=True, default=list)),
                ('requires_supporting_info', models.BooleanField(db_index=True, default=False)),
                ('supporting_info_count', models.PositiveSmallIntegerField(default=0)),
                ('condition_count', models.PositiveSmallIntegerField(default=0)),
                ('exclusion_count', models.PositiveSmallIntegerField(default=0)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fused_benefits', to='nhcx.insuranceplancoverage')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='nhcx.insuranceplan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='nhcx.insuranceplanplan')),
                ('specific_cost_benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fused_rows', to='nhcx.insuranceplanplanspecificcostbenefit')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['insurance_plan', 'plan', 'type_display'], name='nhcx_insura_insuran_afed39_idx'), models.Index(fields=['insurance_plan', 'plan_type_code'], name='nhcx_insura_insuran_ca771b_idx'), models.Index(fields=['insurance_plan', 'coverage_type_code', 'type_code'], name='nhcx_insura_insuran_3467de_idx')],
                'constraints': [models.UniqueConstraint(fields=('insurance_plan', 'plan', 'coverage_type_code', 'type_code'), name='uniq_ipb_per_plan')],
            },
        ),
    ]
