# Generated by Django 6.0 on 2026-05-17 05:04

from django.conf import settings
from django.db import migrations, models


def _dedup_questionnaires(apps, schema_editor):
    """Delete duplicate InsurancePlanQuestionnaire rows (same insurance_plan
    + fhir_id) before the unique constraint is applied. Keeps the lowest id
    per group, which is the first row inserted by the ingestor."""
    Questionnaire = apps.get_model("nhcx", "InsurancePlanQuestionnaire")
    schema_editor.execute(
        """
        DELETE FROM nhcx_insuranceplanquestionnaire a
        USING nhcx_insuranceplanquestionnaire b
        WHERE a.insurance_plan_id = b.insurance_plan_id
          AND a.fhir_id = b.fhir_id
          AND a.fhir_id <> ''
          AND a.id > b.id
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('nhcx', '0014_insuranceplancoverage_type_display_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_dedup_questionnaires, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='insuranceplanquestionnaire',
            constraint=models.UniqueConstraint(fields=('insurance_plan', 'fhir_id'), name='uniq_ip_questionnaire_fhir_id'),
        ),
    ]
