# Generated by Django 6.0 on 2026-06-24 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0078_merge_20260409_1618'),
        ('nhcx', '0022_paymentnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageeligibilityrequest',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.tokenbooking'),
        ),
    ]
