# Generated by Django 6.0 on 2026-06-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhcx', '0023_coverageeligibilityrequest_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='workflow_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='claimresponse',
            name='workflow_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='coverageeligibilityrequest',
            name='workflow_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='coverageeligibilityresponse',
            name='workflow_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='workflow_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
    ]
