# Generated by Django 6.0 on 2026-07-01 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0078_merge_20260409_1618'),
        ('nhcx', '0024_claim_workflow_code_claimresponse_workflow_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='emr.account'),
        ),
        migrations.AddField(
            model_name='claimconsent',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_consents', to='nhcx.claim'),
        ),
    ]
