# Generated by Django 6.0 on 2026-07-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhcx', '0027_child_verification_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimcondition',
            name='discharge_stages_lama_dama_procedure',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='claimcondition',
            name='lama_dama_procedure',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimcondition',
            name='parent_procedure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimcondition',
            name='standalone',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='claimcondition',
            name='unspecified',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
